from schemas.studio import StudioRead
from schemas.auth import (
    ChangePasswordRequest,
    ForgotPasswordRequest,
    GoogleAuthRequest,
    InviteAcceptRequest,
    InviteInfoResponse,
    Login2FARequest,
    LoginRequest,
    OnboardingRequest,
    OtpRequestIn,
    OtpRequestOut,
    OtpVerifyIn,
    OtpVerifyOut,
    RegisterRequest,
    ResetPasswordRequest,
    SelectStudioRequest,
    StudioListItem,
    TokenResponse,
    VerifyEmailRequest,
    WorkingHoursInput,
)
from schemas.clients import (
    ActionMessageOut,
    ActiveSubscriptionOut,
    ActivityPointOut,
    BookingCreatedOut,
    CategoryStatOut,
    ClientCreate,
    ClientCreatedOut,
    ClientFreezeUpdate,
    ClientListItemOut,
    ClientProfileOut,
    ClientRegistrationDateUpdate,
    ClientStatusUpdate,
    ClientTagAction,
    ClientUpdate,
    CountOut,
    EventRecordOut,
    MessageSend,
    NoteCreate,
    NoteCreatedOut,
    NoteOut,
    NoteUpdate,
    OkFrozenOut,
    OkOut,
    TagsOut,
)
from schemas.schedule import BookingCreate
from schemas.settings import (
    StaffCallRequest,
    StaffCreate,
    StaffMessageRequest,
    StaffUpdate,
)
from schemas.staff import (
    StaffCallResponse,
    StaffCancelLessonResponse,
    StaffHall,
    StaffListItem,
    StaffListResponse,
    StaffMessageResponse,
    StaffMonthLesson,
    StaffMonthScheduleResponse,
    StaffMutateResponse,
    StaffProfileResponse,
    StaffStats,
    StaffSummary,
    StaffTodayLesson,
    StaffTodayScheduleResponse,
    StaffWeekScheduleResponse,
    StaffWorkingHoursItem,
)

__all__ = [
    # studio
    "StudioRead",
    # auth
    "ChangePasswordRequest",
    "ForgotPasswordRequest",
    "GoogleAuthRequest",
    "InviteAcceptRequest",
    "InviteInfoResponse",
    "Login2FARequest",
    "LoginRequest",
    "OnboardingRequest",
    "OtpRequestIn",
    "OtpRequestOut",
    "OtpVerifyIn",
    "OtpVerifyOut",
    "RegisterRequest",
    "ResetPasswordRequest",
    "SelectStudioRequest",
    "StudioListItem",
    "TokenResponse",
    "VerifyEmailRequest",
    "WorkingHoursInput",
    # clients — inputs
    "ClientCreate",
    "ClientFreezeUpdate",
    "ClientRegistrationDateUpdate",
    "ClientStatusUpdate",
    "ClientTagAction",
    "ClientUpdate",
    "MessageSend",
    "NoteCreate",
    "NoteUpdate",
    # clients — responses
    "ActionMessageOut",
    "ActiveSubscriptionOut",
    "ActivityPointOut",
    "BookingCreatedOut",
    "CategoryStatOut",
    "ClientCreatedOut",
    "ClientListItemOut",
    "ClientProfileOut",
    "CountOut",
    "EventRecordOut",
    "NoteCreatedOut",
    "NoteOut",
    "OkFrozenOut",
    "OkOut",
    "TagsOut",
    # schedule
    "BookingCreate",
    # settings — staff inputs
    "StaffCallRequest",
    "StaffCreate",
    "StaffMessageRequest",
    "StaffUpdate",
    # staff — responses
    "StaffCallResponse",
    "StaffCancelLessonResponse",
    "StaffHall",
    "StaffListItem",
    "StaffListResponse",
    "StaffMessageResponse",
    "StaffMonthLesson",
    "StaffMonthScheduleResponse",
    "StaffMutateResponse",
    "StaffProfileResponse",
    "StaffStats",
    "StaffSummary",
    "StaffTodayLesson",
    "StaffTodayScheduleResponse",
    "StaffWeekScheduleResponse",
    "StaffWorkingHoursItem",
]
