"""add order_id period_months to invoice, rectoken to card

Revision ID: 12244da73046
Revises: f94b0ed25e01
Create Date: 2026-07-12 20:30:53.494626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12244da73046'
down_revision: Union[str, Sequence[str], None] = 'f94b0ed25e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_invoices', sa.Column('order_id', sa.String(length=100), nullable=True))
    op.add_column('billing_invoices', sa.Column('period_months', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_billing_invoices_order_id'), 'billing_invoices', ['order_id'], unique=True)
    op.add_column('payment_cards', sa.Column('rectoken', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_cards', 'rectoken')
    op.drop_index(op.f('ix_billing_invoices_order_id'), table_name='billing_invoices')
    op.drop_column('billing_invoices', 'period_months')
    op.drop_column('billing_invoices', 'order_id')
    # ### end Alembic commands ###
