"""add studio promo codes

Revision ID: 13f390345e17
Revises: efcf29e955c8
Create Date: 2026-07-18 14:48:48.226841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f390345e17'
down_revision: Union[str, Sequence[str], None] = 'efcf29e955c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("discount_type IN ('percent', 'amount')", name='check_promo_discount_type'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'code', name='uq_promo_code_per_studio')
    )
    op.create_index(op.f('ix_studio_promo_codes_id'), 'studio_promo_codes', ['id'], unique=False)
    op.create_index(op.f('ix_studio_promo_codes_studio_id'), 'studio_promo_codes', ['studio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studio_promo_codes_studio_id'), table_name='studio_promo_codes')
    op.drop_index(op.f('ix_studio_promo_codes_id'), table_name='studio_promo_codes')
    op.drop_table('studio_promo_codes')
    # ### end Alembic commands ###
