"""billing stripe subscriptions

Revision ID: 1453605b4c66
Revises: cb7ba90bd5d0
Create Date: 2026-08-07 22:03:42.686456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1453605b4c66'
down_revision: Union[str, Sequence[str], None] = 'cb7ba90bd5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_invoices', sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True))
    op.add_column('billing_invoices', sa.Column('hosted_invoice_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_billing_invoices_stripe_invoice_id'), 'billing_invoices', ['stripe_invoice_id'], unique=True)
    op.add_column('studio_billing_plans', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('studio_billing_plans', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_studio_billing_plans_stripe_subscription_id'), 'studio_billing_plans', ['stripe_subscription_id'], unique=True)
    op.add_column('studios', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('studios', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('studios', sa.Column('vat_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studios', 'vat_id')
    op.drop_column('studios', 'postal_code')
    op.drop_column('studios', 'country')
    op.drop_index(op.f('ix_studio_billing_plans_stripe_subscription_id'), table_name='studio_billing_plans')
    op.drop_column('studio_billing_plans', 'stripe_subscription_id')
    op.drop_column('studio_billing_plans', 'stripe_customer_id')
    op.drop_index(op.f('ix_billing_invoices_stripe_invoice_id'), table_name='billing_invoices')
    op.drop_column('billing_invoices', 'hosted_invoice_url')
    op.drop_column('billing_invoices', 'stripe_invoice_id')
    # ### end Alembic commands ###
