"""ai_usage and chat message: request_id

Один идентификатор на вопрос человека — вместо связи по соседству строк.
Обе колонки nullable, прежние строки остаются с NULL: к какому прогону они
относились, восстановить нечем, а выдуманный идентификатор склеил бы чужие
вызовы в один «вопрос» и испортил бы ровно ту статистику, ради которой
колонка заводится.

Revision ID: 1e01c7cabef5
Revises: ec88a70bb293
Create Date: 2026-08-24 01:59:55.331642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e01c7cabef5'
down_revision: Union[str, Sequence[str], None] = 'ec88a70bb293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat_messages', sa.Column('request_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_ai_chat_messages_request_id'), 'ai_chat_messages', ['request_id'], unique=False)
    op.add_column('ai_usage', sa.Column('request_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_ai_usage_request_id'), 'ai_usage', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_usage_request_id'), table_name='ai_usage')
    op.drop_column('ai_usage', 'request_id')
    op.drop_index(op.f('ix_ai_chat_messages_request_id'), table_name='ai_chat_messages')
    op.drop_column('ai_chat_messages', 'request_id')
    # ### end Alembic commands ###
