"""offline transaction fees, platform revenue ledger, invoice kind

Revision ID: 200876c346a1
Revises: a5d31f7c60b2
Create Date: 2026-08-08 15:15:24.106393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200876c346a1'
down_revision: Union[str, Sequence[str], None] = 'a5d31f7c60b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_revenue_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_revenue_ledger_external_id'), 'platform_revenue_ledger', ['external_id'], unique=True)
    op.create_index(op.f('ix_platform_revenue_ledger_id'), 'platform_revenue_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_platform_revenue_ledger_occurred_at'), 'platform_revenue_ledger', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_platform_revenue_ledger_source'), 'platform_revenue_ledger', ['source'], unique=False)
    op.create_index(op.f('ix_platform_revenue_ledger_studio_id'), 'platform_revenue_ledger', ['studio_id'], unique=False)
    op.create_table('offline_transaction_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('sale_amount', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('percent_rate', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_transaction_fees_created_at'), 'offline_transaction_fees', ['created_at'], unique=False)
    op.create_index(op.f('ix_offline_transaction_fees_id'), 'offline_transaction_fees', ['id'], unique=False)
    op.create_index(op.f('ix_offline_transaction_fees_invoice_id'), 'offline_transaction_fees', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_offline_transaction_fees_studio_id'), 'offline_transaction_fees', ['studio_id'], unique=False)
    # server_default обязателен: таблицы не пустые, а NOT NULL без значения по
    # умолчанию Postgres на непустой таблице не примет. Дефолт заодно и есть
    # верная трактовка истории — все прежние счета были за тариф, и комиссию с
    # прежних Connect-сессий платформа не удерживала.
    op.add_column('billing_invoices', sa.Column(
        'kind', sa.String(length=20), nullable=False, server_default='subscription',
    ))
    op.create_index(op.f('ix_billing_invoices_kind'), 'billing_invoices', ['kind'], unique=False)
    op.add_column('stripe_checkouts', sa.Column(
        'application_fee', sa.Integer(), nullable=False, server_default='0',
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_checkouts', 'application_fee')
    op.drop_index(op.f('ix_billing_invoices_kind'), table_name='billing_invoices')
    op.drop_column('billing_invoices', 'kind')
    op.drop_index(op.f('ix_offline_transaction_fees_studio_id'), table_name='offline_transaction_fees')
    op.drop_index(op.f('ix_offline_transaction_fees_invoice_id'), table_name='offline_transaction_fees')
    op.drop_index(op.f('ix_offline_transaction_fees_id'), table_name='offline_transaction_fees')
    op.drop_index(op.f('ix_offline_transaction_fees_created_at'), table_name='offline_transaction_fees')
    op.drop_table('offline_transaction_fees')
    op.drop_index(op.f('ix_platform_revenue_ledger_studio_id'), table_name='platform_revenue_ledger')
    op.drop_index(op.f('ix_platform_revenue_ledger_source'), table_name='platform_revenue_ledger')
    op.drop_index(op.f('ix_platform_revenue_ledger_occurred_at'), table_name='platform_revenue_ledger')
    op.drop_index(op.f('ix_platform_revenue_ledger_id'), table_name='platform_revenue_ledger')
    op.drop_index(op.f('ix_platform_revenue_ledger_external_id'), table_name='platform_revenue_ledger')
    op.drop_table('platform_revenue_ledger')
    # ### end Alembic commands ###
