"""ai chat message undo record

Revision ID: 22e80b9d2105
Revises: a3d7e2c94b15
Create Date: 2026-08-18 20:20:08.379915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e80b9d2105'
down_revision: Union[str, Sequence[str], None] = 'a3d7e2c94b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat_messages', sa.Column('undo', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_chat_messages', 'undo')
    # ### end Alembic commands ###
