"""add onboarding

Revision ID: 2abc41bab61e
Revises: 62f13cc54540
Create Date: 2026-06-05 01:39:48.294090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abc41bab61e'
down_revision: Union[str, Sequence[str], None] = '62f13cc54540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studios', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('studios', sa.Column('business_type', sa.String(length=50), nullable=True))
    op.add_column('studios', sa.Column('business_subtype', sa.String(length=50), nullable=True))
    op.add_column('studios', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('studios', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('studios', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_onboarded')
    op.drop_column('studios', 'currency')
    op.drop_column('studios', 'language')
    op.drop_column('studios', 'timezone')
    op.drop_column('studios', 'business_subtype')
    op.drop_column('studios', 'business_type')
    op.drop_column('studios', 'phone')
    # ### end Alembic commands ###
