"""ai usage and action jti

Revision ID: 397ec646abb9
Revises: 147f0556d4c1
Create Date: 2026-08-13 20:46:24.117022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397ec646abb9'
down_revision: Union[str, Sequence[str], None] = '147f0556d4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_micro', sa.Integer(), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('sender_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_billable'), 'ai_usage', ['billable'], unique=False)
    op.create_index(op.f('ix_ai_usage_created_at'), 'ai_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_id'), 'ai_usage', ['id'], unique=False)
    op.create_index('ix_ai_usage_studio_created', 'ai_usage', ['studio_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_studio_id'), 'ai_usage', ['studio_id'], unique=False)
    op.add_column('ai_chat_messages', sa.Column('action_jti', sa.String(length=36), nullable=True))
    # Имя задано явно: с None downgrade не находит, что удалять. В Postgres
    # unique по nullable-колонке допускает сколько угодно NULL — обычные
    # сообщения ограничением не задеты, а второй execute тем же jti отбивает БД.
    op.create_unique_constraint('uq_ai_chat_messages_action_jti', 'ai_chat_messages', ['action_jti'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ai_chat_messages_action_jti', 'ai_chat_messages', type_='unique')
    op.drop_column('ai_chat_messages', 'action_jti')
    op.drop_index(op.f('ix_ai_usage_studio_id'), table_name='ai_usage')
    op.drop_index('ix_ai_usage_studio_created', table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_created_at'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_billable'), table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
