"""add client deposit balance

Revision ID: 3b12646d24b2
Revises: 13f390345e17
Create Date: 2026-07-18 19:39:21.401027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b12646d24b2'
down_revision: Union[str, Sequence[str], None] = '13f390345e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_transactions_client_id'), 'deposit_transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_deposit_transactions_id'), 'deposit_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_deposit_transactions_studio_id'), 'deposit_transactions', ['studio_id'], unique=False)
    op.add_column('client_loyalty_cards', sa.Column('deposit_balance', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_loyalty_cards', 'deposit_balance')
    op.drop_index(op.f('ix_deposit_transactions_studio_id'), table_name='deposit_transactions')
    op.drop_index(op.f('ix_deposit_transactions_id'), table_name='deposit_transactions')
    op.drop_index(op.f('ix_deposit_transactions_client_id'), table_name='deposit_transactions')
    op.drop_table('deposit_transactions')
    # ### end Alembic commands ###
