"""clean user model drop display_name

Revision ID: 62f13cc54540
Revises: b684eb699fc2
Create Date: 2026-06-03 11:20:32.519621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f13cc54540'
down_revision: Union[str, Sequence[str], None] = 'b684eb699fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'studio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('users', 'studio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
