"""sync models with new structure

Revision ID: 6aaea90e19ed
Revises: 2abc41bab61e
Create Date: 2026-06-25 12:55:21.525628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aaea90e19ed'
down_revision: Union[str, Sequence[str], None] = '2abc41bab61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('daily_change', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_studio_id'), 'accounts', ['studio_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_studio_id'), 'activity_logs', ['studio_id'], unique=False)
    op.create_table('booking_channel_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'channel_type', name='uq_booking_channel')
    )
    op.create_index(op.f('ix_booking_channel_configs_id'), 'booking_channel_configs', ['id'], unique=False)
    op.create_index(op.f('ix_booking_channel_configs_studio_id'), 'booking_channel_configs', ['studio_id'], unique=False)
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('counterparty_type', sa.String(length=30), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('deals_count', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_id'), 'counterparties', ['id'], unique=False)
    op.create_index(op.f('ix_counterparties_studio_id'), 'counterparties', ['studio_id'], unique=False)
    op.create_table('daily_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Integer(), nullable=False),
    sa.Column('new_clients', sa.Integer(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('cancelled_bookings', sa.Integer(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'date', name='uq_daily_snapshot_studio_date')
    )
    op.create_index(op.f('ix_daily_metric_snapshots_date'), 'daily_metric_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_daily_metric_snapshots_id'), 'daily_metric_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_daily_metric_snapshots_studio_id'), 'daily_metric_snapshots', ['studio_id'], unique=False)
    op.create_table('financial_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Integer(), nullable=False),
    sa.Column('current_amount', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('tracking_mode', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_goals_id'), 'financial_goals', ['id'], unique=False)
    op.create_index(op.f('ix_financial_goals_studio_id'), 'financial_goals', ['studio_id'], unique=False)
    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_halls_id'), 'halls', ['id'], unique=False)
    op.create_index(op.f('ix_halls_studio_id'), 'halls', ['studio_id'], unique=False)
    op.create_table('loyalty_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('min_threshold', sa.Integer(), nullable=False),
    sa.Column('max_threshold', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_levels_id'), 'loyalty_levels', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_levels_studio_id'), 'loyalty_levels', ['studio_id'], unique=False)
    op.create_table('notification_event_toggles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=10), nullable=False),
    sa.Column('channel_key', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'role', 'event_id', 'channel_key', name='uq_notif_toggle')
    )
    op.create_index(op.f('ix_notification_event_toggles_id'), 'notification_event_toggles', ['id'], unique=False)
    op.create_index(op.f('ix_notification_event_toggles_studio_id'), 'notification_event_toggles', ['studio_id'], unique=False)
    op.create_table('online_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monthly_amount', sa.Integer(), nullable=False),
    sa.Column('monthly_sessions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'channel_type', name='uq_studio_channel')
    )
    op.create_index(op.f('ix_online_channels_id'), 'online_channels', ['id'], unique=False)
    op.create_index(op.f('ix_online_channels_studio_id'), 'online_channels', ['studio_id'], unique=False)
    op.create_table('payment_method_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=30), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('monthly_transactions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'method_type', name='uq_studio_pay_method')
    )
    op.create_index(op.f('ix_payment_method_configs_id'), 'payment_method_configs', ['id'], unique=False)
    op.create_index(op.f('ix_payment_method_configs_studio_id'), 'payment_method_configs', ['studio_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('product_type', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('unit_label', sa.String(length=30), nullable=False),
    sa.Column('badge_type', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_studio_id'), 'products', ['studio_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'name', name='uq_studio_role_name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_studio_id'), 'roles', ['studio_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_studio_id'), 'services', ['studio_id'], unique=False)
    op.create_table('studio_ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('system_prompt', sa.String(length=2000), nullable=True),
    sa.Column('tg_enabled', sa.Boolean(), nullable=False),
    sa.Column('tg_token', sa.String(length=255), nullable=True),
    sa.Column('tg_username', sa.String(length=100), nullable=True),
    sa.Column('tg_tone', sa.String(length=20), nullable=False),
    sa.Column('tg_max_length', sa.Integer(), nullable=False),
    sa.Column('tg_handled_count', sa.Integer(), nullable=False),
    sa.Column('tg_avg_rating', sa.Float(), nullable=False),
    sa.Column('ig_enabled', sa.Boolean(), nullable=False),
    sa.Column('ig_token', sa.String(length=255), nullable=True),
    sa.Column('ig_username', sa.String(length=100), nullable=True),
    sa.Column('ig_tone', sa.String(length=20), nullable=False),
    sa.Column('ig_max_length', sa.Integer(), nullable=False),
    sa.Column('ig_off_hours_only', sa.Boolean(), nullable=False),
    sa.Column('ig_handled_count', sa.Integer(), nullable=False),
    sa.Column('ig_avg_rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_ai_settings_id'), 'studio_ai_settings', ['id'], unique=False)
    op.create_index(op.f('ix_studio_ai_settings_studio_id'), 'studio_ai_settings', ['studio_id'], unique=True)
    op.create_table('studio_backup_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('storage_used_gb', sa.Float(), nullable=False),
    sa.Column('storage_limit_gb', sa.Float(), nullable=False),
    sa.Column('clients_storage_gb', sa.Float(), nullable=False),
    sa.Column('media_storage_gb', sa.Float(), nullable=False),
    sa.Column('docs_storage_gb', sa.Float(), nullable=False),
    sa.Column('auto_backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_retention_days', sa.Integer(), nullable=False),
    sa.Column('last_backup_at', sa.DateTime(), nullable=True),
    sa.Column('last_backup_size_mb', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_backup_settings_id'), 'studio_backup_settings', ['id'], unique=False)
    op.create_index(op.f('ix_studio_backup_settings_studio_id'), 'studio_backup_settings', ['studio_id'], unique=True)
    op.create_table('studio_billing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_staff', sa.Integer(), nullable=False),
    sa.Column('billing_mode', sa.String(length=20), nullable=False),
    sa.Column('percent_rate', sa.Float(), nullable=True),
    sa.Column('fixed_base_amount', sa.Integer(), nullable=True),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.Column('email_receipt_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_before_days', sa.Integer(), nullable=False),
    sa.Column('sms_notification_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_billing_plans_id'), 'studio_billing_plans', ['id'], unique=False)
    op.create_index(op.f('ix_studio_billing_plans_studio_id'), 'studio_billing_plans', ['studio_id'], unique=True)
    op.create_table('studio_booking_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('booking_active', sa.Boolean(), nullable=False),
    sa.Column('prefill_on_booking', sa.Boolean(), nullable=False),
    sa.Column('trainer_confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('client_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('repeat_booking_allowed', sa.Boolean(), nullable=False),
    sa.Column('min_booking_advance_min', sa.Integer(), nullable=False),
    sa.Column('booking_window_days', sa.Integer(), nullable=False),
    sa.Column('cancellation_deadline_min', sa.Integer(), nullable=False),
    sa.Column('widget_accent_color', sa.String(length=7), nullable=False),
    sa.Column('widget_logo_url', sa.String(length=500), nullable=True),
    sa.Column('widget_dark_mode', sa.Boolean(), nullable=False),
    sa.Column('widget_language', sa.String(length=5), nullable=False),
    sa.Column('sms_confirmation', sa.Boolean(), nullable=False),
    sa.Column('reminder_24h', sa.Boolean(), nullable=False),
    sa.Column('reminder_2h', sa.Boolean(), nullable=False),
    sa.Column('review_request', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_booking_settings_id'), 'studio_booking_settings', ['id'], unique=False)
    op.create_index(op.f('ix_studio_booking_settings_studio_id'), 'studio_booking_settings', ['studio_id'], unique=True)
    op.create_table('studio_certificate_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('cert_type', sa.String(length=20), nullable=False),
    sa.Column('expiry_days', sa.Integer(), nullable=False),
    sa.Column('denominations', sa.JSON(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_certificate_configs_id'), 'studio_certificate_configs', ['id'], unique=False)
    op.create_index(op.f('ix_studio_certificate_configs_studio_id'), 'studio_certificate_configs', ['studio_id'], unique=True)
    op.create_table('studio_discount_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('min_purchase_amount', sa.Integer(), nullable=True),
    sa.Column('applies_to_all_services', sa.Boolean(), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('visible_in_cabinet', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_discount_configs_id'), 'studio_discount_configs', ['id'], unique=False)
    op.create_index(op.f('ix_studio_discount_configs_studio_id'), 'studio_discount_configs', ['studio_id'], unique=True)
    op.create_table('studio_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.String(length=30), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'integration_type', name='uq_studio_integration')
    )
    op.create_index(op.f('ix_studio_integrations_id'), 'studio_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_studio_integrations_studio_id'), 'studio_integrations', ['studio_id'], unique=False)
    op.create_table('studio_loyalty_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('program_name', sa.String(length=100), nullable=False),
    sa.Column('points_exchange_rate', sa.Integer(), nullable=False),
    sa.Column('expiry_period', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_loyalty_configs_id'), 'studio_loyalty_configs', ['id'], unique=False)
    op.create_index(op.f('ix_studio_loyalty_configs_studio_id'), 'studio_loyalty_configs', ['studio_id'], unique=True)
    op.create_table('studio_notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('telegram_notifications', sa.Boolean(), nullable=False),
    sa.Column('instagram_notifications', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_emails', sa.Boolean(), nullable=False),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('backup_email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_notification_settings_id'), 'studio_notification_settings', ['id'], unique=False)
    op.create_index(op.f('ix_studio_notification_settings_studio_id'), 'studio_notification_settings', ['studio_id'], unique=True)
    op.create_table('studio_referral_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('referrer_bonus', sa.Integer(), nullable=False),
    sa.Column('new_client_discount', sa.Integer(), nullable=False),
    sa.Column('trigger_condition', sa.String(length=30), nullable=False),
    sa.Column('bonus_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_referral_configs_id'), 'studio_referral_configs', ['id'], unique=False)
    op.create_index(op.f('ix_studio_referral_configs_studio_id'), 'studio_referral_configs', ['studio_id'], unique=True)
    op.create_table('studio_subscription_program_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_freeze', sa.Boolean(), nullable=False),
    sa.Column('allow_transfer', sa.Boolean(), nullable=False),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_subscription_program_configs_id'), 'studio_subscription_program_configs', ['id'], unique=False)
    op.create_index(op.f('ix_studio_subscription_program_configs_studio_id'), 'studio_subscription_program_configs', ['studio_id'], unique=True)
    op.create_table('studio_working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.String(length=5), nullable=False),
    sa.Column('close_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'day_of_week', name='uq_studio_day')
    )
    op.create_index(op.f('ix_studio_working_hours_id'), 'studio_working_hours', ['id'], unique=False)
    op.create_index(op.f('ix_studio_working_hours_studio_id'), 'studio_working_hours', ['studio_id'], unique=False)
    op.create_table('client_loyalty_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['loyalty_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_loyalty_cards_client_id'), 'client_loyalty_cards', ['client_id'], unique=True)
    op.create_index(op.f('ix_client_loyalty_cards_id'), 'client_loyalty_cards', ['id'], unique=False)
    op.create_index(op.f('ix_client_loyalty_cards_studio_id'), 'client_loyalty_cards', ['studio_id'], unique=False)
    op.create_table('fin_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_ext', sa.String(length=10), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('requires_signature', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_documents_id'), 'fin_documents', ['id'], unique=False)
    op.create_index(op.f('ix_fin_documents_studio_id'), 'fin_documents', ['studio_id'], unique=False)
    op.create_table('gift_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('cert_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'used', 'expired')", name='check_cert_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_gift_certificates_client_id'), 'gift_certificates', ['client_id'], unique=False)
    op.create_index(op.f('ix_gift_certificates_id'), 'gift_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_gift_certificates_studio_id'), 'gift_certificates', ['studio_id'], unique=False)
    op.create_table('loyalty_point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_point_transactions_client_id'), 'loyalty_point_transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_loyalty_point_transactions_id'), 'loyalty_point_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_point_transactions_studio_id'), 'loyalty_point_transactions', ['studio_id'], unique=False)
    op.create_table('online_channel_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transactions_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['online_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'period_type', 'period_date', name='uq_channel_metric')
    )
    op.create_index(op.f('ix_online_channel_metrics_channel_id'), 'online_channel_metrics', ['channel_id'], unique=False)
    op.create_index(op.f('ix_online_channel_metrics_id'), 'online_channel_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_online_channel_metrics_studio_id'), 'online_channel_metrics', ['studio_id'], unique=False)
    op.create_table('referral_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('referrer_client_id', sa.Integer(), nullable=True),
    sa.Column('referred_client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bonus_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed', 'cancelled')", name='check_referral_status'),
    sa.ForeignKeyConstraint(['referred_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_client_id')
    )
    op.create_index(op.f('ix_referral_records_id'), 'referral_records', ['id'], unique=False)
    op.create_index(op.f('ix_referral_records_referrer_client_id'), 'referral_records', ['referrer_client_id'], unique=False)
    op.create_index(op.f('ix_referral_records_studio_id'), 'referral_records', ['studio_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('create_booking', sa.Boolean(), nullable=False),
    sa.Column('cancel_booking', sa.Boolean(), nullable=False),
    sa.Column('edit_own_schedule', sa.Boolean(), nullable=False),
    sa.Column('edit_others_schedules', sa.Boolean(), nullable=False),
    sa.Column('view_all_bookings', sa.Boolean(), nullable=False),
    sa.Column('view_staff', sa.Boolean(), nullable=False),
    sa.Column('manage_staff', sa.Boolean(), nullable=False),
    sa.Column('view_contacts', sa.Boolean(), nullable=False),
    sa.Column('edit_client_profiles', sa.Boolean(), nullable=False),
    sa.Column('view_client_history', sa.Boolean(), nullable=False),
    sa.Column('manage_abonements', sa.Boolean(), nullable=False),
    sa.Column('apply_discounts', sa.Boolean(), nullable=False),
    sa.Column('send_messages', sa.Boolean(), nullable=False),
    sa.Column('export_database', sa.Boolean(), nullable=False),
    sa.Column('delete_clients', sa.Boolean(), nullable=False),
    sa.Column('view_revenue', sa.Boolean(), nullable=False),
    sa.Column('view_detailed_finances', sa.Boolean(), nullable=False),
    sa.Column('issue_refunds', sa.Boolean(), nullable=False),
    sa.Column('edit_prices', sa.Boolean(), nullable=False),
    sa.Column('view_salaries', sa.Boolean(), nullable=False),
    sa.Column('edit_salaries', sa.Boolean(), nullable=False),
    sa.Column('view_basic_reports', sa.Boolean(), nullable=False),
    sa.Column('view_full_reports', sa.Boolean(), nullable=False),
    sa.Column('export_reports', sa.Boolean(), nullable=False),
    sa.Column('edit_studio_settings', sa.Boolean(), nullable=False),
    sa.Column('manage_integrations', sa.Boolean(), nullable=False),
    sa.Column('manage_pricelist', sa.Boolean(), nullable=False),
    sa.Column('manage_notifications', sa.Boolean(), nullable=False),
    sa.Column('access_ai', sa.Boolean(), nullable=False),
    sa.Column('manage_roles', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=True)
    op.create_table('subscription_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('class_count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('per_visit_price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['studio_subscription_program_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_packages_config_id'), 'subscription_packages', ['config_id'], unique=False)
    op.create_index(op.f('ix_subscription_packages_id'), 'subscription_packages', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_packages_studio_id'), 'subscription_packages', ['studio_id'], unique=False)
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('preview', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_sessions_id'), 'ai_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_studio_id'), 'ai_chat_sessions', ['studio_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_id'), 'api_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_api_tokens_studio_id'), 'api_tokens', ['studio_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_id'), 'billing_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_studio_id'), 'billing_invoices', ['studio_id'], unique=False)
    op.create_table('client_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_notes_client_id'), 'client_notes', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_notes_id'), 'client_notes', ['id'], unique=False)
    op.create_index(op.f('ix_client_notes_studio_id'), 'client_notes', ['studio_id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('op_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_counterparty_id'), 'operations', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    op.create_index(op.f('ix_operations_product_id'), 'operations', ['product_id'], unique=False)
    op.create_index(op.f('ix_operations_studio_id'), 'operations', ['studio_id'], unique=False)
    op.create_index(op.f('ix_operations_trainer_id'), 'operations', ['trainer_id'], unique=False)
    op.create_table('payment_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=False),
    sa.Column('card_brand', sa.String(length=20), nullable=False),
    sa.Column('card_expiry', sa.String(length=5), nullable=False),
    sa.Column('cardholder_name', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_cards_id'), 'payment_cards', ['id'], unique=False)
    op.create_index(op.f('ix_payment_cards_user_id'), 'payment_cards', ['user_id'], unique=False)
    op.create_table('salary_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('rate_snapshot', sa.Float(), nullable=False),
    sa.Column('rate_type_snapshot', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_payments_id'), 'salary_payments', ['id'], unique=False)
    op.create_index(op.f('ix_salary_payments_studio_id'), 'salary_payments', ['studio_id'], unique=False)
    op.create_index(op.f('ix_salary_payments_user_id'), 'salary_payments', ['user_id'], unique=False)
    op.create_table('staff_working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.String(length=5), nullable=False),
    sa.Column('close_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_of_week', name='uq_staff_day')
    )
    op.create_index(op.f('ix_staff_working_hours_id'), 'staff_working_hours', ['id'], unique=False)
    op.create_index(op.f('ix_staff_working_hours_user_id'), 'staff_working_hours', ['user_id'], unique=False)
    op.create_table('studio_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('max_attendees', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('upcoming', 'completed', 'cancelled')", name='check_event_status'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_events_id'), 'studio_events', ['id'], unique=False)
    op.create_index(op.f('ix_studio_events_studio_id'), 'studio_events', ['studio_id'], unique=False)
    op.create_index(op.f('ix_studio_events_trainer_id'), 'studio_events', ['trainer_id'], unique=False)
    op.create_table('studio_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_tasks_id'), 'studio_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_studio_tasks_studio_id'), 'studio_tasks', ['studio_id'], unique=False)
    op.create_table('trainer_sales_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('target_revenue', sa.Integer(), nullable=False),
    sa.Column('target_sessions', sa.Integer(), nullable=False),
    sa.Column('actual_revenue', sa.Integer(), nullable=False),
    sa.Column('actual_sessions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_start', 'period_end', name='uq_trainer_goal_period')
    )
    op.create_index(op.f('ix_trainer_sales_goals_id'), 'trainer_sales_goals', ['id'], unique=False)
    op.create_index(op.f('ix_trainer_sales_goals_studio_id'), 'trainer_sales_goals', ['studio_id'], unique=False)
    op.create_index(op.f('ix_trainer_sales_goals_user_id'), 'trainer_sales_goals', ['user_id'], unique=False)
    op.create_table('user_services',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'service_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('last_active', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_id'), 'ai_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.create_table('event_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=100), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['studio_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'client_id', name='uq_event_client')
    )
    op.create_index(op.f('ix_event_attendees_client_id'), 'event_attendees', ['client_id'], unique=False)
    op.create_index(op.f('ix_event_attendees_event_id'), 'event_attendees', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_attendees_id'), 'event_attendees', ['id'], unique=False)
    op.create_index(op.f('ix_event_attendees_studio_id'), 'event_attendees', ['studio_id'], unique=False)
    op.create_table('product_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('is_new_client', sa.Boolean(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sales_client_id'), 'product_sales', ['client_id'], unique=False)
    op.create_index(op.f('ix_product_sales_id'), 'product_sales', ['id'], unique=False)
    op.create_index(op.f('ix_product_sales_operation_id'), 'product_sales', ['operation_id'], unique=False)
    op.create_index(op.f('ix_product_sales_product_id'), 'product_sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_sales_studio_id'), 'product_sales', ['studio_id'], unique=False)
    op.create_table('studio_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('nps_score', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['studio_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_reviews_client_id'), 'studio_reviews', ['client_id'], unique=False)
    op.create_index(op.f('ix_studio_reviews_event_id'), 'studio_reviews', ['event_id'], unique=False)
    op.create_index(op.f('ix_studio_reviews_id'), 'studio_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_studio_reviews_lesson_id'), 'studio_reviews', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_studio_reviews_studio_id'), 'studio_reviews', ['studio_id'], unique=False)
    op.add_column('client_subscriptions', sa.Column('is_frozen', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('client_subscriptions', sa.Column('frozen_at', sa.DateTime(), nullable=True))
    op.add_column('client_subscriptions', sa.Column('freeze_until', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('avatar_color', sa.String(length=7), nullable=True))
    op.add_column('clients', sa.Column('status', sa.String(length=20), server_default=sa.text("'new'"), nullable=False))
    op.add_column('clients', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('clients', sa.Column('last_visit_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('clients', sa.Column('source', sa.String(length=30), nullable=True))
    op.alter_column('clients', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('lessons', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('hall_id', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('status', sa.String(length=20), server_default=sa.text("'scheduled'"), nullable=False))
    op.create_index(op.f('ix_lessons_hall_id'), 'lessons', ['hall_id'], unique=False)
    op.create_index(op.f('ix_lessons_service_id'), 'lessons', ['service_id'], unique=False)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'lessons', 'halls', ['hall_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'lessons', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.add_column('reservations', sa.Column('review_text', sa.String(length=500), nullable=True))
    op.add_column('reservations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('reservations', sa.Column('booking_channel', sa.String(length=20), nullable=True))
    op.add_column('reservations', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('reservations', sa.Column('cancellation_reason', sa.String(length=300), nullable=True))
    op.add_column('studios', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('studios', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('studios', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('studios', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('studios', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('studios', sa.Column('date_format', sa.String(length=20), nullable=True))
    op.add_column('studios', sa.Column('first_day_of_week', sa.String(length=10), nullable=True))
    op.add_column('studios', sa.Column('journal_time_step', sa.Integer(), server_default=sa.text('30'), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('salary', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('rate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('rate_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('avg_rating', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_online', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('two_fa_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('theme', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('accent_color', sa.String(length=7), nullable=True))
    op.add_column('users', sa.Column('account_label', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_gradient', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('primary_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_primary_user_id'), 'users', ['primary_user_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['primary_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_primary_user_id'), table_name='users')
    op.drop_column('users', 'primary_user_id')
    op.drop_column('users', 'avatar_gradient')
    op.drop_column('users', 'department')
    op.drop_column('users', 'account_label')
    op.drop_column('users', 'accent_color')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'two_fa_enabled')
    op.drop_column('users', 'is_online')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'avg_rating')
    op.drop_column('users', 'rate_type')
    op.drop_column('users', 'rate')
    op.drop_column('users', 'salary')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'last_name')
    op.drop_column('studios', 'journal_time_step')
    op.drop_column('studios', 'first_day_of_week')
    op.drop_column('studios', 'date_format')
    op.drop_column('studios', 'logo_url')
    op.drop_column('studios', 'address')
    op.drop_column('studios', 'website')
    op.drop_column('studios', 'email')
    op.drop_column('studios', 'description')
    op.drop_column('reservations', 'cancellation_reason')
    op.drop_column('reservations', 'cancelled_at')
    op.drop_column('reservations', 'booking_channel')
    op.drop_column('reservations', 'created_at')
    op.drop_column('reservations', 'review_text')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_service_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_hall_id'), table_name='lessons')
    op.drop_column('lessons', 'status')
    op.drop_column('lessons', 'service_id')
    op.drop_column('lessons', 'hall_id')
    op.drop_column('lessons', 'teacher_id')
    op.alter_column('clients', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('clients', 'source')
    op.drop_column('clients', 'is_active')
    op.drop_column('clients', 'last_visit_date')
    op.drop_column('clients', 'tags')
    op.drop_column('clients', 'status')
    op.drop_column('clients', 'avatar_color')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'birth_date')
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'last_name')
    op.drop_column('client_subscriptions', 'freeze_until')
    op.drop_column('client_subscriptions', 'frozen_at')
    op.drop_column('client_subscriptions', 'is_frozen')
    op.drop_index(op.f('ix_studio_reviews_studio_id'), table_name='studio_reviews')
    op.drop_index(op.f('ix_studio_reviews_lesson_id'), table_name='studio_reviews')
    op.drop_index(op.f('ix_studio_reviews_id'), table_name='studio_reviews')
    op.drop_index(op.f('ix_studio_reviews_event_id'), table_name='studio_reviews')
    op.drop_index(op.f('ix_studio_reviews_client_id'), table_name='studio_reviews')
    op.drop_table('studio_reviews')
    op.drop_index(op.f('ix_product_sales_studio_id'), table_name='product_sales')
    op.drop_index(op.f('ix_product_sales_product_id'), table_name='product_sales')
    op.drop_index(op.f('ix_product_sales_operation_id'), table_name='product_sales')
    op.drop_index(op.f('ix_product_sales_id'), table_name='product_sales')
    op.drop_index(op.f('ix_product_sales_client_id'), table_name='product_sales')
    op.drop_table('product_sales')
    op.drop_index(op.f('ix_event_attendees_studio_id'), table_name='event_attendees')
    op.drop_index(op.f('ix_event_attendees_id'), table_name='event_attendees')
    op.drop_index(op.f('ix_event_attendees_event_id'), table_name='event_attendees')
    op.drop_index(op.f('ix_event_attendees_client_id'), table_name='event_attendees')
    op.drop_table('event_attendees')
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_id'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_services')
    op.drop_index(op.f('ix_trainer_sales_goals_user_id'), table_name='trainer_sales_goals')
    op.drop_index(op.f('ix_trainer_sales_goals_studio_id'), table_name='trainer_sales_goals')
    op.drop_index(op.f('ix_trainer_sales_goals_id'), table_name='trainer_sales_goals')
    op.drop_table('trainer_sales_goals')
    op.drop_index(op.f('ix_studio_tasks_studio_id'), table_name='studio_tasks')
    op.drop_index(op.f('ix_studio_tasks_id'), table_name='studio_tasks')
    op.drop_table('studio_tasks')
    op.drop_index(op.f('ix_studio_events_trainer_id'), table_name='studio_events')
    op.drop_index(op.f('ix_studio_events_studio_id'), table_name='studio_events')
    op.drop_index(op.f('ix_studio_events_id'), table_name='studio_events')
    op.drop_table('studio_events')
    op.drop_index(op.f('ix_staff_working_hours_user_id'), table_name='staff_working_hours')
    op.drop_index(op.f('ix_staff_working_hours_id'), table_name='staff_working_hours')
    op.drop_table('staff_working_hours')
    op.drop_index(op.f('ix_salary_payments_user_id'), table_name='salary_payments')
    op.drop_index(op.f('ix_salary_payments_studio_id'), table_name='salary_payments')
    op.drop_index(op.f('ix_salary_payments_id'), table_name='salary_payments')
    op.drop_table('salary_payments')
    op.drop_index(op.f('ix_payment_cards_user_id'), table_name='payment_cards')
    op.drop_index(op.f('ix_payment_cards_id'), table_name='payment_cards')
    op.drop_table('payment_cards')
    op.drop_index(op.f('ix_operations_trainer_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_studio_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_product_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_counterparty_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_client_notes_studio_id'), table_name='client_notes')
    op.drop_index(op.f('ix_client_notes_id'), table_name='client_notes')
    op.drop_index(op.f('ix_client_notes_client_id'), table_name='client_notes')
    op.drop_table('client_notes')
    op.drop_index(op.f('ix_billing_invoices_studio_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_studio_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_studio_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_id'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    op.drop_index(op.f('ix_subscription_packages_studio_id'), table_name='subscription_packages')
    op.drop_index(op.f('ix_subscription_packages_id'), table_name='subscription_packages')
    op.drop_index(op.f('ix_subscription_packages_config_id'), table_name='subscription_packages')
    op.drop_table('subscription_packages')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_referral_records_studio_id'), table_name='referral_records')
    op.drop_index(op.f('ix_referral_records_referrer_client_id'), table_name='referral_records')
    op.drop_index(op.f('ix_referral_records_id'), table_name='referral_records')
    op.drop_table('referral_records')
    op.drop_index(op.f('ix_online_channel_metrics_studio_id'), table_name='online_channel_metrics')
    op.drop_index(op.f('ix_online_channel_metrics_id'), table_name='online_channel_metrics')
    op.drop_index(op.f('ix_online_channel_metrics_channel_id'), table_name='online_channel_metrics')
    op.drop_table('online_channel_metrics')
    op.drop_index(op.f('ix_loyalty_point_transactions_studio_id'), table_name='loyalty_point_transactions')
    op.drop_index(op.f('ix_loyalty_point_transactions_id'), table_name='loyalty_point_transactions')
    op.drop_index(op.f('ix_loyalty_point_transactions_client_id'), table_name='loyalty_point_transactions')
    op.drop_table('loyalty_point_transactions')
    op.drop_index(op.f('ix_gift_certificates_studio_id'), table_name='gift_certificates')
    op.drop_index(op.f('ix_gift_certificates_id'), table_name='gift_certificates')
    op.drop_index(op.f('ix_gift_certificates_client_id'), table_name='gift_certificates')
    op.drop_table('gift_certificates')
    op.drop_index(op.f('ix_fin_documents_studio_id'), table_name='fin_documents')
    op.drop_index(op.f('ix_fin_documents_id'), table_name='fin_documents')
    op.drop_table('fin_documents')
    op.drop_index(op.f('ix_client_loyalty_cards_studio_id'), table_name='client_loyalty_cards')
    op.drop_index(op.f('ix_client_loyalty_cards_id'), table_name='client_loyalty_cards')
    op.drop_index(op.f('ix_client_loyalty_cards_client_id'), table_name='client_loyalty_cards')
    op.drop_table('client_loyalty_cards')
    op.drop_index(op.f('ix_studio_working_hours_studio_id'), table_name='studio_working_hours')
    op.drop_index(op.f('ix_studio_working_hours_id'), table_name='studio_working_hours')
    op.drop_table('studio_working_hours')
    op.drop_index(op.f('ix_studio_subscription_program_configs_studio_id'), table_name='studio_subscription_program_configs')
    op.drop_index(op.f('ix_studio_subscription_program_configs_id'), table_name='studio_subscription_program_configs')
    op.drop_table('studio_subscription_program_configs')
    op.drop_index(op.f('ix_studio_referral_configs_studio_id'), table_name='studio_referral_configs')
    op.drop_index(op.f('ix_studio_referral_configs_id'), table_name='studio_referral_configs')
    op.drop_table('studio_referral_configs')
    op.drop_index(op.f('ix_studio_notification_settings_studio_id'), table_name='studio_notification_settings')
    op.drop_index(op.f('ix_studio_notification_settings_id'), table_name='studio_notification_settings')
    op.drop_table('studio_notification_settings')
    op.drop_index(op.f('ix_studio_loyalty_configs_studio_id'), table_name='studio_loyalty_configs')
    op.drop_index(op.f('ix_studio_loyalty_configs_id'), table_name='studio_loyalty_configs')
    op.drop_table('studio_loyalty_configs')
    op.drop_index(op.f('ix_studio_integrations_studio_id'), table_name='studio_integrations')
    op.drop_index(op.f('ix_studio_integrations_id'), table_name='studio_integrations')
    op.drop_table('studio_integrations')
    op.drop_index(op.f('ix_studio_discount_configs_studio_id'), table_name='studio_discount_configs')
    op.drop_index(op.f('ix_studio_discount_configs_id'), table_name='studio_discount_configs')
    op.drop_table('studio_discount_configs')
    op.drop_index(op.f('ix_studio_certificate_configs_studio_id'), table_name='studio_certificate_configs')
    op.drop_index(op.f('ix_studio_certificate_configs_id'), table_name='studio_certificate_configs')
    op.drop_table('studio_certificate_configs')
    op.drop_index(op.f('ix_studio_booking_settings_studio_id'), table_name='studio_booking_settings')
    op.drop_index(op.f('ix_studio_booking_settings_id'), table_name='studio_booking_settings')
    op.drop_table('studio_booking_settings')
    op.drop_index(op.f('ix_studio_billing_plans_studio_id'), table_name='studio_billing_plans')
    op.drop_index(op.f('ix_studio_billing_plans_id'), table_name='studio_billing_plans')
    op.drop_table('studio_billing_plans')
    op.drop_index(op.f('ix_studio_backup_settings_studio_id'), table_name='studio_backup_settings')
    op.drop_index(op.f('ix_studio_backup_settings_id'), table_name='studio_backup_settings')
    op.drop_table('studio_backup_settings')
    op.drop_index(op.f('ix_studio_ai_settings_studio_id'), table_name='studio_ai_settings')
    op.drop_index(op.f('ix_studio_ai_settings_id'), table_name='studio_ai_settings')
    op.drop_table('studio_ai_settings')
    op.drop_index(op.f('ix_services_studio_id'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_roles_studio_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_studio_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_method_configs_studio_id'), table_name='payment_method_configs')
    op.drop_index(op.f('ix_payment_method_configs_id'), table_name='payment_method_configs')
    op.drop_table('payment_method_configs')
    op.drop_index(op.f('ix_online_channels_studio_id'), table_name='online_channels')
    op.drop_index(op.f('ix_online_channels_id'), table_name='online_channels')
    op.drop_table('online_channels')
    op.drop_index(op.f('ix_notification_event_toggles_studio_id'), table_name='notification_event_toggles')
    op.drop_index(op.f('ix_notification_event_toggles_id'), table_name='notification_event_toggles')
    op.drop_table('notification_event_toggles')
    op.drop_index(op.f('ix_loyalty_levels_studio_id'), table_name='loyalty_levels')
    op.drop_index(op.f('ix_loyalty_levels_id'), table_name='loyalty_levels')
    op.drop_table('loyalty_levels')
    op.drop_index(op.f('ix_halls_studio_id'), table_name='halls')
    op.drop_index(op.f('ix_halls_id'), table_name='halls')
    op.drop_table('halls')
    op.drop_index(op.f('ix_financial_goals_studio_id'), table_name='financial_goals')
    op.drop_index(op.f('ix_financial_goals_id'), table_name='financial_goals')
    op.drop_table('financial_goals')
    op.drop_index(op.f('ix_daily_metric_snapshots_studio_id'), table_name='daily_metric_snapshots')
    op.drop_index(op.f('ix_daily_metric_snapshots_id'), table_name='daily_metric_snapshots')
    op.drop_index(op.f('ix_daily_metric_snapshots_date'), table_name='daily_metric_snapshots')
    op.drop_table('daily_metric_snapshots')
    op.drop_index(op.f('ix_counterparties_studio_id'), table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_id'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index(op.f('ix_booking_channel_configs_studio_id'), table_name='booking_channel_configs')
    op.drop_index(op.f('ix_booking_channel_configs_id'), table_name='booking_channel_configs')
    op.drop_table('booking_channel_configs')
    op.drop_index(op.f('ix_activity_logs_studio_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_accounts_studio_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
