"""add client offers

Revision ID: 8ae844566f25
Revises: fb9bb1077858
Create Date: 2026-07-20 11:47:14.076965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae844566f25'
down_revision: Union[str, Sequence[str], None] = 'fb9bb1077858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("discount_type IN ('percent', 'amount')", name='check_offer_discount_type'),
    sa.CheckConstraint("reason IN ('scenario', 'manual', 'campaign')", name='check_offer_reason'),
    sa.CheckConstraint("scope IN ('renewal', 'any')", name='check_offer_scope'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_offers_client_id'), 'client_offers', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_offers_id'), 'client_offers', ['id'], unique=False)
    op.create_index(op.f('ix_client_offers_studio_id'), 'client_offers', ['studio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_offers_studio_id'), table_name='client_offers')
    op.drop_index(op.f('ix_client_offers_id'), table_name='client_offers')
    op.drop_index(op.f('ix_client_offers_client_id'), table_name='client_offers')
    op.drop_table('client_offers')
    # ### end Alembic commands ###
