"""offline fee postpay: accrual, invoice due date, terms consent

Revision ID: aacd10dbeacb
Revises: b3cedf9ea0c0
Create Date: 2026-08-09 14:53:57.163514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacd10dbeacb'
down_revision: Union[str, Sequence[str], None] = 'b3cedf9ea0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offline_transaction_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('sale_amount', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('percent_rate', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_transaction_fees_created_at'), 'offline_transaction_fees', ['created_at'], unique=False)
    op.create_index(op.f('ix_offline_transaction_fees_id'), 'offline_transaction_fees', ['id'], unique=False)
    op.create_index(op.f('ix_offline_transaction_fees_invoice_id'), 'offline_transaction_fees', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_offline_transaction_fees_studio_id'), 'offline_transaction_fees', ['studio_id'], unique=False)
    # server_default обязателен: таблица не пустая, а NOT NULL без значения по
    # умолчанию Postgres на непустой таблице не примет. Дефолт заодно и верная
    # трактовка истории — все прежние счета были за тариф.
    op.add_column('billing_invoices', sa.Column(
        'kind', sa.String(length=20), nullable=False, server_default='subscription',
    ))
    op.add_column('billing_invoices', sa.Column('due_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_billing_invoices_due_at'), 'billing_invoices', ['due_at'], unique=False)
    op.create_index(op.f('ix_billing_invoices_kind'), 'billing_invoices', ['kind'], unique=False)
    op.add_column('studio_billing_plans', sa.Column('percent_terms_accepted_at', sa.DateTime(), nullable=True))
    op.add_column('studio_billing_plans', sa.Column('percent_terms_rate', sa.Float(), nullable=True))
    op.add_column('studio_billing_plans', sa.Column('percent_terms_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_billing_plans', 'percent_terms_version')
    op.drop_column('studio_billing_plans', 'percent_terms_rate')
    op.drop_column('studio_billing_plans', 'percent_terms_accepted_at')
    op.drop_index(op.f('ix_billing_invoices_kind'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_due_at'), table_name='billing_invoices')
    op.drop_column('billing_invoices', 'due_at')
    op.drop_column('billing_invoices', 'kind')
    op.drop_index(op.f('ix_offline_transaction_fees_studio_id'), table_name='offline_transaction_fees')
    op.drop_index(op.f('ix_offline_transaction_fees_invoice_id'), table_name='offline_transaction_fees')
    op.drop_index(op.f('ix_offline_transaction_fees_id'), table_name='offline_transaction_fees')
    op.drop_index(op.f('ix_offline_transaction_fees_created_at'), table_name='offline_transaction_fees')
    op.drop_table('offline_transaction_fees')
    # ### end Alembic commands ###
