"""user otp fields

Revision ID: ab036aec5531
Revises: dd87070a896b
Create Date: 2026-07-28 02:13:56.145369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab036aec5531'
down_revision: Union[str, Sequence[str], None] = 'dd87070a896b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('otp_action', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_action')
    op.drop_column('users', 'otp_code_hash')
    # ### end Alembic commands ###
