"""drop offline fee collection, keep connect fee ledger

Revision ID: b3cedf9ea0c0
Revises: 200876c346a1
Create Date: 2026-08-09 13:33:13.527108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3cedf9ea0c0'
down_revision: Union[str, Sequence[str], None] = '200876c346a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offline_transaction_fees_created_at'), table_name='offline_transaction_fees')
    op.drop_index(op.f('ix_offline_transaction_fees_id'), table_name='offline_transaction_fees')
    op.drop_index(op.f('ix_offline_transaction_fees_invoice_id'), table_name='offline_transaction_fees')
    op.drop_index(op.f('ix_offline_transaction_fees_studio_id'), table_name='offline_transaction_fees')
    op.drop_table('offline_transaction_fees')
    op.drop_index(op.f('ix_billing_invoices_kind'), table_name='billing_invoices')
    op.drop_column('billing_invoices', 'kind')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_invoices', sa.Column('kind', sa.VARCHAR(length=20), server_default=sa.text("'subscription'::character varying"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_billing_invoices_kind'), 'billing_invoices', ['kind'], unique=False)
    op.create_table('offline_transaction_fees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('studio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fee_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('percent_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('offline_transaction_fees_client_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], name=op.f('offline_transaction_fees_invoice_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], name=op.f('offline_transaction_fees_studio_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('offline_transaction_fees_pkey'))
    )
    op.create_index(op.f('ix_offline_transaction_fees_studio_id'), 'offline_transaction_fees', ['studio_id'], unique=False)
    op.create_index(op.f('ix_offline_transaction_fees_invoice_id'), 'offline_transaction_fees', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_offline_transaction_fees_id'), 'offline_transaction_fees', ['id'], unique=False)
    op.create_index(op.f('ix_offline_transaction_fees_created_at'), 'offline_transaction_fees', ['created_at'], unique=False)
    # ### end Alembic commands ###
