"""stripe connect account and checkouts

Revision ID: ba9511ee5bbb
Revises: e4a2b7c19d63
Create Date: 2026-08-01 17:53:26.000899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9511ee5bbb'
down_revision: Union[str, Sequence[str], None] = 'e4a2b7c19d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_checkouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_checkouts_id'), 'stripe_checkouts', ['id'], unique=False)
    op.create_index(op.f('ix_stripe_checkouts_session_id'), 'stripe_checkouts', ['session_id'], unique=True)
    op.create_index(op.f('ix_stripe_checkouts_studio_id'), 'stripe_checkouts', ['studio_id'], unique=False)
    op.add_column('online_channels', sa.Column('account_id', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('online_channels', 'account_id')
    op.drop_index(op.f('ix_stripe_checkouts_studio_id'), table_name='stripe_checkouts')
    op.drop_index(op.f('ix_stripe_checkouts_session_id'), table_name='stripe_checkouts')
    op.drop_index(op.f('ix_stripe_checkouts_id'), table_name='stripe_checkouts')
    op.drop_table('stripe_checkouts')
    # ### end Alembic commands ###
