"""user session ip user agent revoked

Revision ID: dd87070a896b
Revises: 4c198703405b
Create Date: 2026-07-28 01:02:11.824126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd87070a896b'
down_revision: Union[str, Sequence[str], None] = '4c198703405b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('user_sessions', sa.Column('user_agent', sa.String(length=300), nullable=True))
    op.add_column('user_sessions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_column('user_sessions', 'revoked_at')
    op.drop_column('user_sessions', 'created_at')
    op.drop_column('user_sessions', 'user_agent')
    op.drop_column('user_sessions', 'ip_address')
    # ### end Alembic commands ###
