"""ai_usage: escalation reason and source model

Обе колонки nullable, и прежние строки остаются с NULL намеренно: причину
эскалации для них никто не записывал, и вычислить её задним числом нечем.
`escalated = true, escalation_reason IS NULL` читается как «эскалация была,
причина не сохранена» — это честнее, чем проставить всем правдоподобную.

Revision ID: ec88a70bb293
Revises: 22e80b9d2105
Create Date: 2026-08-24 01:45:12.127961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec88a70bb293'
down_revision: Union[str, Sequence[str], None] = '22e80b9d2105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage', sa.Column('escalation_reason', sa.String(length=32), nullable=True))
    op.add_column('ai_usage', sa.Column('escalation_from_model', sa.String(length=60), nullable=True))
    op.create_index('ix_ai_usage_escalation', 'ai_usage', ['escalation_reason'], unique=False, postgresql_where=sa.text('escalation_reason IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_usage_escalation', table_name='ai_usage', postgresql_where=sa.text('escalation_reason IS NOT NULL'))
    op.drop_column('ai_usage', 'escalation_from_model')
    op.drop_column('ai_usage', 'escalation_reason')
    # ### end Alembic commands ###
