"""action proposals

Revision ID: f061d8187ad4
Revises: a99d09a5abc6
Create Date: 2026-09-01 15:26:47.105092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f061d8187ad4'
down_revision: Union[str, Sequence[str], None] = 'a99d09a5abc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('created_reservation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['customer_identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['channel_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_action_proposals_id'), 'action_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_action_proposals_studio_id'), 'action_proposals', ['studio_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_thread_id'), 'action_proposals', ['thread_id'], unique=False)
    op.create_index('ix_proposal_expires', 'action_proposals', ['expires_at'], unique=False)
    op.create_index('ix_proposal_live', 'action_proposals', ['studio_id', 'thread_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proposal_live', table_name='action_proposals')
    op.drop_index('ix_proposal_expires', table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_thread_id'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_studio_id'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_id'), table_name='action_proposals')
    op.drop_table('action_proposals')
    # ### end Alembic commands ###
