"""Add phone and display_name to users

Revision ID: f87731d7999f
Revises: 7d6b29d0683f
Create Date: 2026-06-02 22:20:49.210096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87731d7999f'
down_revision: Union[str, Sequence[str], None] = '7d6b29d0683f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
