"""ai_usage response language

На каком языке ответили и почему. Две колонки, обе nullable: у строк, записанных
до этой миграции, языка не было, и придумывать его задним числом нельзя —
неизвестность честнее выдуманного значения.

Нужны не только для отчётов. В мессенджерах агент вызывается по ОДНОМУ
сообщению, истории диалога у него нет, и «ОК» после чешского вопроса без этой
колонки падало бы на язык студии. Отсюда же читается последний надёжный язык
разговора — по той же тройке studio_id + surface + sender_ref, что и антиспам,
так что языки двух клиентов одной студии не смешиваются.

Revision ID: ff072a9ffb45
Revises: e2f0b7c39d54
Create Date: 2026-08-27 23:29:55.536044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff072a9ffb45'
down_revision: Union[str, Sequence[str], None] = 'e2f0b7c39d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage', sa.Column('response_language', sa.String(length=8), nullable=True))
    op.add_column('ai_usage', sa.Column('language_source', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_usage', 'language_source')
    op.drop_column('ai_usage', 'response_language')
    # ### end Alembic commands ###
